#!/bin/bash

# Quick Test Script for Auth & WebSocket Fixes
# Run this after starting both servers

echo "================================"
echo "🧪 Testing Authentication Fix"
echo "================================"
echo ""

echo "📝 Test Checklist:"
echo ""
echo "1. Clear localStorage:"
echo "   Open browser console and run: localStorage.clear()"
echo ""
echo "2. Register a new user:"
echo "   → Go to: http://localhost:5173/register"
echo "   → Create account with:"
echo "     Email: test@example.com"
echo "     Password: test123"
echo "   → Should login automatically"
echo ""
echo "3. Check browser console:"
echo "   ✅ Should see: 'TradesTable: WebSocket connected'"
echo "   ❌ Should NOT see: 'verifyIdToken() expects...'"
echo ""
echo "4. Check backend console:"
echo "   ✅ Should see: '🔌 Client connected: [socket-id]'"
echo "   ❌ Should NOT see: 'Auth middleware error'"
echo ""
echo "5. Test logout:"
echo "   → Click logout"
echo "   → Should return to login page"
echo "   → Token cleared from localStorage"
echo ""
echo "6. Test login again:"
echo "   → Login with same credentials"
echo "   → Should work without errors"
echo ""
echo "================================"
echo "🔌 Testing WebSocket Resilience"
echo "================================"
echo ""
echo "1. Open dashboard with trades table"
echo "2. Stop backend server (Ctrl+C)"
echo "3. Wait 2 seconds"
echo "4. Start backend server again"
echo ""
echo "Expected behavior:"
echo "   ✅ Frontend shows: 'Disconnected: transport close'"
echo "   ✅ Then shows: 'TradesTable: WebSocket connected'"
echo "   ❌ Should NOT spam ECONNABORTED errors"
echo ""
echo "================================"
echo "✅ If all checks pass, the fix is working!"
echo "================================"
